services:
  db:
    image: redis:8-alpine
    command: redis-server --save "" --appendonly no
    networks:
      - aisra-net

  mqtt-broker:
    image: eclipse-mosquitto:2.1-alpine
    ports:
      - "${MQTT_PORT}:1883"
    networks:
      - aisra-net

  heuristic-web:
    build:
      context: ./backend/src
      dockerfile: AIsra.HeuristicLibWeb.Server/Dockerfile
    volumes:
      - ./certs/localhost.pfx:/app/cert.pfx
    env_file:
      - .env
    networks:
      - aisra-net

  aisra-web:
    build:
      context: ./backend/src
      dockerfile: AIsra.Web/Dockerfile
    ports:
      - "${AGENT_PORT}:${AGENT_PORT}"
    volumes:
      - ./certs/localhost.pfx:/app/cert.pfx
    env_file:
      - .env
    environment:
      REDIS_HOST: db
      MQTT_HOST: mqtt-broker
      HEURISTIC_LIB_SERVER_URL: "https://heuristic-web:5001"
    depends_on:
      db:
        condition: service_started
      mqtt-broker:
        condition: service_started
      heuristic-web:
        condition: service_started
    networks:
      - aisra-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_API_URL: "${PUBLIC_API_URL}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - aisra-web

networks:
  aisra-net:
    driver: bridge
