services:
  db:
    image: redis:8-alpine
    command: redis-server --save "" --appendonly no
    networks:
      - heal-net

  mqtt-broker:
    image: eclipse-mosquitto:2.1-alpine
    ports:
      - "${MQTT_PORT}:1883"
    networks:
      - heal-net

  heuristic-web:
    build:
      context: ./backend/src
      dockerfile: HEAL.HeuristicWeb.Server/Dockerfile
    volumes:
      - ./certs/localhost.pfx:/app/cert.pfx
    env_file:
      - .env
    networks:
      - heal-net

  agent-web:
    build:
      context: ./backend/src
      dockerfile: HEAL.HeuristicAgent.Web/Dockerfile
    ports:
      - "${AGENT_PORT}:${AGENT_PORT}"
    volumes:
      - ./certs/localhost.pfx:/app/cert.pfx
    env_file:
      - .env
    environment:
      REDIS_HOST: db
      MQTT_HOST: mqtt-broker
      HEURISTIC_LIB_SERVER_URL: "https://heuristic-web:5001"
    depends_on:
      db:
        condition: service_started
      mqtt-broker:
        condition: service_started
      heuristic-web:
        condition: service_started
    networks:
      - heal-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_API_URL: "https://localhost:${AGENT_PORT}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - agent-web

networks:
  heal-net:
    driver: bridge
