@startuml

actor "User" as user

package heuristic-agent-frontend {
    component "Web Client" as webClient
}

user .r.> webClient

package HeuristicAgent {
'    package Host {
        interface "HTTP" as agentApi
        component "Web Server" as agentServer
        component "Chat Client" as chatClient
        component "MCP Client" as mcpClient
        component "MQTT Client" as mqttClient
        component "Model Evaluator" as eval
'    }
'    package Server {
        component "Redis Client" as redisClient
        component "MCP Server" as mcpServer
        interface "MCP" as mcp
'    }

    agentApi -r- agentServer
    redisClient <-d- mcpServer
    agentServer -d-> chatClient
    chatClient --> mcpClient
    mcpServer -r- mcp
    mcpClient .l.> mcp
    mqttClient --> redisClient
    mqttClient -r-> eval
    eval -d-> chatClient
    mcpServer -u-> eval
    eval -> redisClient

    note bottom of eval {
        Notifies the
        agent when
        the quality
        drops
    }
}

webClient ..> agentApi

component "MQTT Broker" as mqttBroker #line.dashed
interface "MQTT" as mqtt
component "Data Stream Generator" as dsg #line.dashed

mqttBroker -d- mqtt
mqttClient .l.> mqtt
dsg .r.> mqtt

database "Redis" as redis #line.dashed
interface "RESP" as resp

note bottom of redis {
    Stores models and
    data from stream
}

redisClient .l.> resp
resp -l- redis

cloud {
    component "OpenRouter" as openRouter #line.dashed
    component "LLM" as llm #line.dashed
    interface "HTTP" as openRouterApi

    openRouterApi -r- openRouter
    openRouter .u.> llm
}

chatClient .r.> openRouterApi

package HeuristicLibAdapter {
    interface "HeuristicLib Adapter" as adapter
    component "HeuristicLib Client" as libClient
    component "HeuristicLib gRPC Client" as grpcClient
    component "HeuristicLib REST Client" as restClient

    adapter -- libClient
    adapter -- grpcClient
    adapter -- restClient
}

mcpServer --( adapter

package HeuristicWeb {
    component "HeuristicLib REST API" as restApi
    component "HeuristicLib gRPC Service" as grpcService
    interface "gRPC" as grpc
    interface "HTTP" as http

    grpc -l- grpcService
    http -r- restApi
    restApi -[hidden]r- grpcService
    restApi -[hidden]r- grpcService
}

package HeuristicLibWrapper {
    component "Symbolic Regression Runner" as runner
}

package HeuristicLib #line.dashed

libClient --> runner
grpcService --> runner
restApi --> runner
grpcClient ..> grpc
restClient ..> http
runner --> HeuristicLib

@enduml
